# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Sudheesh Singanamalla
tagline:             'Personalized Diary'
description: 		 'Sudheeshs blog that is maintained as a personal diary as a part of EPICS project for review by faculty incharge'
url: 				 http://gearsystems.github.io/       
baseurl:             /sudheesh/
paginate:            5

# About/contact
author:
  name:              Sudheesh Singanamalla
  url:               https://twitter.com/sudheesh001
  email:             sudheesh95@gmail.com

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/gearsystems/sudheesh
